export const samplePotentialRecipe = {
  id: 1234567890,
  name: "Pandan Crème Brûlée",
  cookTime: null,
  servings: 6,
  instructions: "1. Preheat the oven to 325°F (160°C).\n2. In a large bowl, whisk together the egg yolks and ¾–1 cup of sugar (depending on your sweetness preference) until smooth.\n3. Add the heavy cream to a medium pot and warm over medium heat just until steam starts rising from the cream, about 3 minutes. DO NOT let it boil! Turn off the heat.\n4. While whisking, slowly pour about ½ cup of the hot cream into the egg and sugar mixture (this is called tempering, allowing us to gently heat the eggs without causing them to curdle).\n5. Slowly pour the egg mixture into the pot with the remaining heavy cream and whisk to combine. Add the pandan extract and vanilla, then remove the pot from the heat.\n6. Place 6 medium ramekins in a baking dish with sides the same height (or taller) than the ramekins. Dividing evenly, ladle the egg mixture through a fine-mesh sieve into the ramekins to catch any clumps and create a super-smooth consistency. If you’d like, skim off excess foam from the surface.\n7. Carefully pour the hot water into the pan, being careful not to splash into the ramekins (the water bath will help the crème brûlée cook evenly).\n8. Carefully transfer the pan with the ramekins to the oven. If desired, throw the ice cubes into the bottom of the oven to create a more humid baking environment.\n9. Bake for 35–40 minutes, or until the custard has set and the centers are only slightly jiggly.\n10. Remove from the oven and let cool at room temperature for 2 hours, then remove the ramekins from the water bath, cover, and refrigerate overnight.\n11. The next day, sprinkle 1 tablespoon of sugar over each crème brûlée and use a kitchen torch to melt until bubbly and dark golden. Let sit for a few minutes to solidify.\n12. Top with your fruits of choice and serve.\n13. Enjoy!",
  imgURL: "https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/445157.jpg",
  description: "Have you ever tried pandan? Pandan is a plant used in many Asian cuisines, prized for its vibrant green leaves! It tastes like the love child of grass, vanilla, and coconut–super delish! This is probably the best crème brûlée I’ve ever had and pandan is truly the star of the show. I experimented with different ways of adding more pandan to the dish, but to be honest, using pandan extract was the easiest method, it yielded the creamiest outcome, AND had the best flavor.",
  authors: [
    { id: 1, name: "Source: Tasty API - Rapid API" }
  ]
};